// src/components/SiteHeader.svelte
<script lang="ts">
  const navigation = [
    { href: "/blog/", label: "blogs" },
    { href: "/about/", label: "about" },
  ];
</script>

<header class="site-header">
  <div class="header-inner">
    <a class="brand" href="/" aria-label="홈">
      jaeyoung lee
    </a>

    <nav class="header-nav" aria-label="주요 메뉴">
      {#each navigation as item (item.href)}
        <a href={item.href}>
          {item.label}
        </a>
      {/each}
    </nav>
  </div>
</header>

// src/components/site-header.tsx
import Link from "next/link";

const navigation = [
  { href: "/blog/", label: "blogs" },
  { href: "/about/", label: "about" },
];

export function SiteHeader() {
  return (
    <header className="site-header">
      <div className="header-inner">
        <Link className="brand" href="/" aria-label="홈">
          jaeyoung lee
        </Link>

        <nav className="header-nav" aria-label="주요 메뉴">
          {navigation.map((item) => (
            <Link href={item.href} key={item.href}>
              {item.label}
            </Link>
          ))}
        </nav>
      </div>
    </header>
  );
}
