// src/app/blog/[slug]/page.tsx
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { compileMDX } from "next-mdx-remote/rsc";
import {
  ArrowLeft,
  CalendarDays,
  Clock3,
} from "lucide-react";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";
import rehypeSlug from "rehype-slug";
import remarkGfm from "remark-gfm";
import { CodeCopyEnhancer } from "@/components/code-copy-enhancer";
import { ArticleToc } from "@/components/article-toc";
import { GiscusComments } from "@/components/giscus-comments";
import { mdxComponents } from "@/components/mdx-components";
import { YouTubeEmbed } from "@/components/youtube-embed";
import { getAllPosts, getPost } from "@/lib/posts";
import { formatDate } from "@/lib/post-shared";
import { remarkMermaid } from "@/lib/remark-mermaid";
import { siteConfig } from "@/lib/site";

type PageProps = {
  params: Promise<{ slug: string }>;
};

export const dynamicParams = false;

export function generateStaticParams() {
  const posts = getAllPosts();

  // Static export requires at least one parameter for a dynamic route.
  return posts.length > 0
    ? posts.map((post) => ({ slug: post.slug }))
    : [{ slug: "__empty__" }];
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) return {};

  const image = post.coverYoutubeId
    ? `https://i.ytimg.com/vi/${post.coverYoutubeId}/hqdefault.jpg`
    : (post.cover ?? "/images/editorial-backend-desk.jpg");

  return {
    title: post.title,
    description: post.description,
    alternates: {
      canonical: `/blog/${post.slug}/`,
    },
    openGraph: {
      type: "article",
      locale: "ko_KR",
      url: `/blog/${post.slug}/`,
      title: post.title,
      description: post.description,
      publishedTime: new Date(post.publishedAt).toISOString(),
      modifiedTime: post.updatedAt
        ? new Date(post.updatedAt).toISOString()
        : undefined,
      tags: post.tags,
      images: [
        {
          url: image,
          width: 1800,
          height: 1029,
          alt: post.coverAlt ?? post.title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
      images: [image],
    },
  };
}

export default async function PostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) notFound();

  const { content } = await compileMDX({
    source: post.content,
    components: mdxComponents,
    options: {
      mdxOptions: {
        remarkPlugins: [remarkGfm, remarkMermaid],
        rehypePlugins: [
          rehypeSlug,
          [rehypeAutolinkHeadings, { behavior: "wrap" }],
          [
            rehypePrettyCode,
            {
              theme: "github-dark-dimmed",
              keepBackground: false,
            },
          ],
        ],
      },
    },
  });

  const image = post.coverYoutubeId
    ? `https://i.ytimg.com/vi/${post.coverYoutubeId}/hqdefault.jpg`
    : (post.cover ?? "/images/editorial-backend-desk.jpg");
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.description,
    datePublished: new Date(post.publishedAt).toISOString(),
    dateModified: new Date(
      post.updatedAt ?? post.publishedAt,
    ).toISOString(),
    inLanguage: "ko-KR",
    author: {
      "@type": "Person",
      name: siteConfig.author.name,
      url: siteConfig.author.github,
    },
    image: new URL(image, siteConfig.url).toString(),
    mainEntityOfPage: `${siteConfig.url}/blog/${post.slug}/`,
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <article>
        <header className="article-header">
          <div className="article-header-inner">
            <Link className="back-link" href="/blog/">
              <ArrowLeft size={15} /> 전체 글
            </Link>
            <h1>{post.title}</h1>
            <p className="description">{post.description}</p>
            <div className="article-meta">
              <span>
                <CalendarDays size={15} />
                {formatDate(post.publishedAt)}
              </span>
              <span>
                <Clock3 size={15} />
                {post.readingMinutes}분 읽기
              </span>
              {post.updatedAt && (
                <span>수정 {formatDate(post.updatedAt)}</span>
              )}
            </div>
            <ul className="tag-list">
              {post.tags.map((tag) => (
                <li className="tag" key={tag}>
                  {tag}
                </li>
              ))}
            </ul>
          </div>
        </header>

        {post.coverYoutubeId ? (
          <div className="article-cover article-video-cover">
            <YouTubeEmbed
              videoId={post.coverYoutubeId}
              title={post.coverYoutubeTitle ?? post.title}
            />
          </div>
        ) : post.cover ? (
          <figure className="article-cover">
            <Image
              src={post.cover}
              alt={post.coverAlt ?? post.title}
              width={1800}
              height={1029}
              priority
            />
            {post.coverAlt && <figcaption>{post.coverAlt}</figcaption>}
          </figure>
        ) : null}

        <div className="article-grid">
          {post.headings.length > 0 && (
            <ArticleToc headings={post.headings} />
          )}
          <div className="prose">{content}</div>
        </div>
      </article>
      <CodeCopyEnhancer />
      <GiscusComments />
    </>
  );
}

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import { ArrowLeft, CalendarDays, Clock3 } from "lucide-svelte";
  import ArticleToc from "$components/ArticleToc.svelte";
  import CodeCopyEnhancer from "$components/CodeCopyEnhancer.svelte";
  import MermaidHandler from "$components/MermaidHandler.svelte";
  import GiscusComments from "$components/GiscusComments.svelte";
  import { formatDate } from "$lib/post-shared";
  import { siteConfig } from "$lib/site";
  import type { PageData } from "./$types";

  let { data }: { data: PageData } = $props();
  const post = $derived(data.post);

  const image = $derived(
    post.coverYoutubeId
      ? `https://i.ytimg.com/vi/${post.coverYoutubeId}/hqdefault.jpg`
      : post.cover ?? "/images/editorial-backend-desk.jpg",
  );

  const jsonLd = $derived(
    JSON.stringify({
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      headline: post.title,
      description: post.description,
      datePublished: new Date(post.publishedAt).toISOString(),
      dateModified: new Date(
        post.updatedAt ?? post.publishedAt,
      ).toISOString(),
      inLanguage: "ko-KR",
      author: {
        "@type": "Person",
        name: siteConfig.author.name,
        url: siteConfig.author.github,
      },
      image: new URL(image, siteConfig.url).toString(),
      mainEntityOfPage: `${siteConfig.url}/blog/${post.slug}/`,
    }),
  );
</script>

<svelte:head>
  <title>{post.title} | {siteConfig.name}</title>
  <meta name="description" content={post.description} />
  <link rel="canonical" href={`${siteConfig.url}/blog/${post.slug}/`} />
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="ko_KR" />
  <meta property="og:url" content={`${siteConfig.url}/blog/${post.slug}/`} />
  <meta property="og:title" content={post.title} />
  <meta property="og:description" content={post.description} />
  <meta
    property="article:published_time"
    content={new Date(post.publishedAt).toISOString()}
  />
  {#if post.updatedAt}
    <meta
      property="article:modified_time"
      content={new Date(post.updatedAt).toISOString()}
    />
  {/if}
  {#each post.tags as tag (tag)}
    <meta property="article:tag" content={tag} />
  {/each}
  <meta property="og:image" content={image} />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={post.title} />
  <meta name="twitter:description" content={post.description} />
  <meta name="twitter:image" content={image} />
  {#if jsonLd}
    <script type="application/ld+json">
      {@html jsonLd}
    </script>
  {/if}
</svelte:head>

<article>
  <header class="article-header">
    <div class="article-header-inner">
      <a class="back-link" href="/blog/">
        <ArrowLeft size={15} /> 전체 글
      </a>
      <h1>{post.title}</h1>
      <p class="description">{post.description}</p>
      <div class="article-meta">
        <span>
          <CalendarDays size={15} />
          {formatDate(post.publishedAt)}
        </span>
        <span>
          <Clock3 size={15} />
          {post.readingMinutes}분 읽기
        </span>
        {#if post.updatedAt}
          <span>수정 {formatDate(post.updatedAt)}</span>
        {/if}
      </div>
      <ul class="tag-list">
        {#each post.tags as tag (tag)}
          <li class="tag">{tag}</li>
        {/each}
      </ul>
    </div>
  </header>

  {#if post.coverYoutubeId}
    <div class="article-cover article-video-cover">
      <figure class="youtube-embed">
        <div class="youtube-embed-frame">
          <iframe
            src={`https://www.youtube-nocookie.com/embed/${post.coverYoutubeId}`}
            title={post.coverYoutubeTitle ?? post.title}
            loading="lazy"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen
          ></iframe>
        </div>
      </figure>
    </div>
  {:else if post.cover}
    <figure class="article-cover">
      <img
        src={post.cover}
        alt={post.coverAlt ?? post.title}
        width="1800"
        height="1029"
        loading="eager"
        decoding="async"
      />
      {#if post.coverAlt}
        <figcaption>{post.coverAlt}</figcaption>
      {/if}
    </figure>
  {/if}

  <div class="article-grid">
    {#if post.headings.length > 0}
      <ArticleToc headings={post.headings} />
    {/if}
    <div class="prose">
      {@html post.html}
    </div>
  </div>
</article>

<CodeCopyEnhancer />
<MermaidHandler />
<GiscusComments />
